### ISSUE TITLE
Any chance to redo it for another platform

### ISSUE THREAD

**Issue by MrBambix** [KD0RC/Teensy-Maestro-for-Flex-6000-radios#2]
Hi,

Very nice project and was seeing if I could build a version of it. However getting a Teensy 4.1 is extremely difficult at this time, have you considered another platform for this great project maybe ?

regards,
Leo de Blaauw
 
PA1LDB

**Comment by KD0RC** [comment]
Hi Leo,
Thanks for your interest in the project!  The Teensy 4.1 with the ethernet function has recently come back to being available in the US at the PJRC.com site.  I believe that they are now starting to show up again in Europe, but I don’t know which vendors have them or what the lead times are.

The project could probably be ported to a different platform, but it would not be a trivial exercise.  I rely heavily on the libraries that are optimized for the Teensy (especially the Ethernet routines), so all of that would need to be worked out.

73,
Len, KD0RC

From: ***@***.***>
Sent: Tuesday, August 16, 2022 6:13 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [KD0RC/Teensy-Maestro-for-Flex-6000-radios] Any chance to redo it for another platform (Issue #2)


Hi,

Very nice project and was seeing if I could build a version of it. However getting a Teensy 4.1 is extremely difficult at this time, have you considered another platform for this great project maybe ?

regards,
Leo de Blaauw

PA1LDB
